//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 12:30:23 PM CET 
//


package it.polito.dp2.BIB.sol2.exercise1.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uniqueness" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max_depth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="relationships" type="{}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uniqueness",
    "maxDepth",
    "relationships"
})
@XmlRootElement(name = "traverseRequest")
public class TraverseRequest {

    @XmlElement(required = true)
    protected String uniqueness;
    @XmlElement(name = "max_depth", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxDepth;
    protected List<RelationshipType> relationships;

    /**
     * Gets the value of the uniqueness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueness() {
        return uniqueness;
    }

    /**
     * Sets the value of the uniqueness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueness(String value) {
        this.uniqueness = value;
    }

    /**
     * Gets the value of the maxDepth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxDepth() {
        return maxDepth;
    }

    /**
     * Sets the value of the maxDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxDepth(BigInteger value) {
        this.maxDepth = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationships property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationships().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationshipType }
     * 
     * 
     */
    public List<RelationshipType> getRelationships() {
        if (relationships == null) {
            relationships = new ArrayList<RelationshipType>();
        }
        return this.relationships;
    }

}
