//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.04 at 05:47:58 PM CET 
//


package it.polito.dp2.BIB.sol2.jaxb.crossref;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.BIB.sol2.jaxb.crossref package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.BIB.sol2.jaxb.crossref
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link Items.PublishedPrint }
     * 
     */
    public Items.PublishedPrint createItemsPublishedPrint() {
        return new Items.PublishedPrint();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link CrossrefResult }
     * 
     */
    public CrossrefResult createCrossrefResult() {
        return new CrossrefResult();
    }

    /**
     * Create an instance of {@link ISBNType }
     * 
     */
    public ISBNType createISBNType() {
        return new ISBNType();
    }

    /**
     * Create an instance of {@link CrossrefMessage }
     * 
     */
    public CrossrefMessage createCrossrefMessage() {
        return new CrossrefMessage();
    }

}
