//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 11:59:01 AM CET 
//


package it.polito.dp2.BIB.sol1.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BiblioItemsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BiblioItemsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="article" type="{http://pad.polito.it/dp2/biblio}ArticleType"/>
 *         &lt;element name="book" type="{http://pad.polito.it/dp2/biblio}BookType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BiblioItemsType", propOrder = {
    "articleOrBook"
})
public class BiblioItemsType {

    @XmlElements({
        @XmlElement(name = "article", type = ArticleType.class),
        @XmlElement(name = "book", type = BookType.class)
    })
    protected List<ItemType> articleOrBook;

    /**
     * Gets the value of the articleOrBook property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the articleOrBook property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArticleOrBook().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArticleType }
     * {@link BookType }
     * 
     * 
     */
    public List<ItemType> getArticleOrBook() {
        if (articleOrBook == null) {
            articleOrBook = new ArrayList<ItemType>();
        }
        return this.articleOrBook;
    }

}
