//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 11:59:01 AM CET 
//


package it.polito.dp2.BIB.sol1.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.BIB.sol1.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Biblio_QNAME = new QName("http://pad.polito.it/dp2/biblio", "biblio");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.BIB.sol1.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link BiblioType }
     * 
     */
    public BiblioType createBiblioType() {
        return new BiblioType();
    }

    /**
     * Create an instance of {@link BookType }
     * 
     */
    public BookType createBookType() {
        return new BookType();
    }

    /**
     * Create an instance of {@link BiblioItemsType }
     * 
     */
    public BiblioItemsType createBiblioItemsType() {
        return new BiblioItemsType();
    }

    /**
     * Create an instance of {@link BiblioJournalsType }
     * 
     */
    public BiblioJournalsType createBiblioJournalsType() {
        return new BiblioJournalsType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ChapterType }
     * 
     */
    public ChapterType createChapterType() {
        return new ChapterType();
    }

    /**
     * Create an instance of {@link ArticleType }
     * 
     */
    public ArticleType createArticleType() {
        return new ArticleType();
    }

    /**
     * Create an instance of {@link JournalType.Issue }
     * 
     */
    public JournalType.Issue createJournalTypeIssue() {
        return new JournalType.Issue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiblioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pad.polito.it/dp2/biblio", name = "biblio")
    public JAXBElement<BiblioType> createBiblio(BiblioType value) {
        return new JAXBElement<BiblioType>(_Biblio_QNAME, BiblioType.class, null, value);
    }

}
